apiVersion: v1
kind: Service
metadata:
  name: common-svc
spec:
  type: NodePort
  selector:
    app: common-pod
  ports:
    - name: customer-port-mapping
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30090
    - name: admin-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: common-pod
  name: common-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-pod
  template:
    metadata:
      labels:
        app: common-pod
    spec:
      containers:
      - image: nivedsuresh/vnilusso-customer:1.0
        name: customer
        volumeMounts:
          - name: product-images
            mountPath: /workspace/product-images
        ports:
          - containerPort: 8081
        env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DATASOURCE_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres_db
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres_username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres_password
            - name: DATASOURCE_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres_port
            - name: DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres_host
      - image: nivedsuresh/vnilusso-admin:1.1
        name: admin
        volumeMounts:
          - name: product-images
            mountPath: /workspace/product-images
        ports:
          - containerPort: 8080
        env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DATASOURCE_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres_db
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres_username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres_password
            - name: DATASOURCE_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres_port
            - name: DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: postgres_host
      volumes:
        - name: product-images
          persistentVolumeClaim:
            claimName: images-pvc
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/images

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
spec:
  volumeName: images-pv
  storageClassName: 'standard'
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---