
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  postgres_host: "postgres-svc"
  postgres_port: "5432"
  postgres_db: "vnilusso"

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  postgres_username: cG9zdGdyZXM=
  postgres_password: MjI1NQ==
